version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - aws s3 cp s3://testebs-resources/application.properties ./src/main/resources
  build:
    commands:
      - mvn clean package -Dspring.profiles.active=test
  post_build:
    commands:
      - mv target/*.war ./testebs.war

artifacts:
  files:
    - testebs.war